###### Translations here #######

# SEO
title: "PapaKoala: Esercizi di stimolazione precoce per neonati facili da usare"
tagline: Esercizi di stimolazione precoce per neonati facili da usare
description: Attività di stimolazione precoce per i bambini per promuovere lo sviluppo del cervello, fornire esperienze sensoriali precoci e costruire un senso di fiducia.
# Pagina di titolo
page_title: "Nutri il tuo piccolo genio: Scopri il viaggio di stimolazione precoce di PapaKoala"
app_name: "PapaKoala: Sviluppo del neonato"
app_price: Abbonamento
app_subtitle: Intraprendi un viaggio verso la potenza cerebrale e il legame con PapaKoala per i bambini da 0 a 1 anno.
app_description: "Gli anni dell'infanzia sono una finestra di opportunità eccezionale per lo sviluppo del cervello di un bambino. Questo è il momento migliore per accendere il loro potenziale intellettuale e gettare le basi per l'apprendimento permanente. \nPapaKoala, la tua guida personale alla stimolazione precoce, ti consente di nutrire la crescita cognitiva del tuo piccolo e creare una profonda connessione emotiva con loro."

# Elenco delle funzionalità               Modifica, aggiungi o rimuovi le funzionalità da presentare.
features:
  
 - title: Sblocca il potere della stimolazione precoce
 description: Immergi il tuo bambino in un mondo di esperienze stimolanti che promuovono lo sviluppo del cervello e risvegliano i sensi. Le attività accuratamente curate di PapaKoala, guidate da ricerche di sviluppo di esperti, introducono il tuo piccolo in una sinfonia di immagini, suoni e tatto, stimolando i loro percorsi neurali e ponendo le basi per il successo futuro.
 fontawesome_icon_name: bambino
  

 - title: Sperimenta la gioia dell'apprendimento interattivo
 description: Dì addio agli esercizi monotoni ed abbraccia la natura divertente e coinvolgente delle attività interattive di PapaKoala. I nostri tutorial basati su video forniscono una guida chiara e rendono l'apprendimento un'esperienza piacevole per genitori e bambini.
 fontawesome_icon_name: cervello

 - title: Nutrire un legame di amore e fiducia
 description: La stimolazione precoce va oltre lo sviluppo cognitivo; si tratta di creare un legame sicuro e amorevole tra te e il tuo bambino. Le attività di PapaKoala sottolineano il tatto, la forma più fondamentale di coinvolgimento infantile, favorendo la fiducia, la sicurezza e una profonda connessione emotiva.
 fontawesome_icon_name: cuore



############## end of translations block #####





# App Info
ios_app_id                                : 1540490806                               # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                    # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").
spanish_page_link                         : https://es.papakoala.com                                                                                      
japan_page_link                           : https://jap.papakoala.com
english_page_link                         : https://papakoala.com  
chinese_page_link                         : https://cn.papakoala.com
german_page_link                          : https://ger.papakoala.com
southkorea_page_link                      : https://kor.papakoala.com
french_page_link                          : https://fr.papakoala.com
italian_page_link                         : https://it.papakoala.com
hindi_page_link                           : https://hi.papakoala.com
portuguese_page_link                      : https://pt.papakoala.com
brazil_page_link                          : https://ptbra.papakoala.com

app_icon                                  :                      # assets/appicon.png  Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.


enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : PapaKoala                                
your_link                                 : https://papakoala.com                     
your_city                                 :                              
email_address                             : hello@papakoala.com
facebook_username                         :                                           
instagram_username                        : papakoala_app
twitter_username                          : 
github_username                           : 
youtube_username                          : 




# Theme Settings
topbar_color                              : "#6EC8FF"
topbar_transparency                       : 0.4
topbar_title_color                        : "#444B54"

cover_image                               : assets/header_lowres.jpg                  # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 0.6

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#FFEAC1"

app_title_color                           : "#393e44"
app_price_color                           : "#FFFFFF"
app_description_color                     : "#ffffff"

app_language_color                        : "#FFEAC1"

feature_title_color                       : "#FFEAC1"
feature_text_color                        : "#ffffff"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#FA6694"

social_icons_foreground_color             : "#BF82EC"
social_icons_background_color             : "#FFFFFF"

footer_text_color                         : "#000000"




# Google services
google_analytics: G-D89JL3TSP6




# url: papakoala.com




####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

plugins:
  - jekyll-seo-tag

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
